### ISSUE TITLE
Plugin not working Redmine 2.5.0

### ISSUE THREAD

**Issue by timjcraig** [stpl/redmine_mention_plugin#1]
Mention plugin installed successfully and is listed in plugins. Auto does not list users suggest and does not add user to watch list send email when enter @<username>

Environment:
  Redmine version      2.5.0.stable
  Ruby version            1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version             3.2.17

**Comment by Nyholm** [comment]
I do also have problems. I cant say if it is Redmine, Ruby or something else... 

```
Redmine version                2.5.1.stable
  Ruby version                   1.8.7-p358 (2012-02-08) [x86_64-linux]
  Rails version                  3.2.17
```

Output

```
$ rake redmine:plugins NAME=redmine_mention_plugin RAILS_ENV=production
rake aborted!
/opt/redmine/plugins/redmine_mention_plugin/lib/mention/user_patch.rb:9: syntax error, unexpected '>'
        scope :with_name,->(name) { where('LCASE(CONCAT(f...
                           ^
/opt/redmine/plugins/redmine_mention_plugin/lib/mention/user_patch.rb:9: syntax error, unexpected '{', expecting kEND
...   scope :with_name,->(name) { where('LCASE(CONCAT(firstname...
                              ^
/opt/redmine/plugins/redmine_mention_plugin/lib/mention/user_patch.rb:9: syntax error, unexpected '}', expecting kEND
```

**Comment by stpl** [comment]
@Nyholm, You are on old Ruby version. Plugin supports 1.9.2 and above. This issue exists with the older ruby versions. You can refer this http://stackoverflow.com/questions/7780240/syntax-error-unexpected-expecting-in-stripe-form-using-rails-3 .

**Comment by Nyholm** [comment]
Thank you @stpl  for quick reply.
