### ISSUE TITLE
Doesn't render in issue description (only works in notes)

### ISSUE THREAD

**Issue by rozzin** [stpl/redmine_mention_plugin#2]
Typing "@foo" when editing the issue _description_ field (either when creating a new issue or when editing an existing issue) does pop up a user-selector, and selecting a user from the list does insert "[~foo] " into the description, but:
- the "[~foo]" is not rendered into a hyperlinked proper name when the description is rendered; it's just shown as the un-parsed "[~foo]".
- the addition of "[~foo]" in the issue description field doesn't cause the user to be added to the watcher list

It seems like those features should work when the "[~foo]" is written into the description field, or the user-selection popup should not be shown when editing the description.

**Comment by rozzin** [comment]
I just created a pull request with a patch to fix this, along with patches to fix a couple of other closely-related nits: https://github.com/stpl/redmine_mention_plugin/pull/4

**Comment by stpl** [comment]
Thanks @rozzin , I have merged pull request along with some other fixes.

**Comment by rozzin** [comment]
Thanks. Just pulled your master branch onto my server—seems to work. Now I'll have happy users ☺
