### ISSUE TITLE
Doesn't parse/render "[~foo]" forms in previews or e-mail notices

### ISSUE THREAD

**Issue by rozzin** [stpl/redmine_mention_plugin#5]
In e-mail notices generated by issue updates, the "[~foo]" forms are rendered literally rather than as hyperlinked proper-name expansions like they should be.

The same is true of the _preview_ area when editing issues to add notes.

**Comment by stpl** [comment]
@rozzin , Have fixed this. Please try with latest code and let me know if you face any issue, else we can close this.

**Comment by rozzin** [comment]
Works for me w/ Redmine 2.5.1. Thanks!
